### ISSUE TITLE
mod compatibility issue 

### ISSUE THREAD

**Issue by wzsjc2020** [LordDeatHunter/ColorMeOutlines#12]
I am currently working on a mod and this mod also changes block outline render. However I did not find your mod published in maven repository. So it's little bit had to compact with your mod. Only thing I can do right now it to load your config.txt  file every 20 game ticks. That would be too much calculation. I wonder if you can publish your mod to maven that would be easier for me and other mod creators to compact with your mod.

**Comment by LordDeatHunter** [comment]
No such plans for the time being, but you can have a look at [Cursemaven](https://cursemaven.com/) or [Modrinth maven](https://support.modrinth.com/en/articles/8801191-modrinth-maven).
LMK if that helps :)

**Comment by wzsjc2020** [comment]
Thanks for your help. Cursemaven works pretty well.
